# ???????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/数据库名字?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username:
    password:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #password:
  rabbitmq:
    host:
    username:
    password:
    publisher-returns: true
    publisher-confirms: true
  mail:
#    host: smtp.qq.com
#    protocol: smtp
#    default-encoding: utf-8
#    # password是授权码。需要定期更新
#    password:
#    username:
#    port: 587

  profiles:
    active: default

# ???
server:
  #这里就要用这个端口，因为前端项目默认就是用的这个端口
  port: 8088

# ??myabtis plus?mapper?xml???????
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml


shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
config:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
